### ISSUE TITLE
cargo should install it properly

### ISSUE THREAD

**Issue by kaolin** [Ablexxive/wikit#1]
having to `ln -s` seems silly when all the tooling is there (unless I misunderstand). and actually that's a good way to accidentally uninstall it when you clean. ;) :)

**Comment by Ablexxive** [comment]
Seems like you can `cargo install --path ./` from within the wikit directory already! Can update the README.md to do that instead of symlink.

**Comment by kaolin** [comment]
Win! :)

-kaolin fire
-http://erif.org/
